name: 🚀 Feature Request
description: Schlage eine neue Idee oder Verbesserung für das Projekt vor.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank für deinen Vorschlag! Bitte fülle die folgenden Felder so präzise wie möglich aus.

  - type: textarea
    id: problem
    attributes:
      label: Das Problem (The Why)
      description: Welches Problem möchtest du lösen? Beschreibe den aktuellen unbefriedigenden Zustand.
      placeholder: "Kunden brechen ab, weil sie X nicht finden..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Die Lösung / Das Ziel
      description: Was soll erreicht werden?
      placeholder: "Wir sollten einen Button hinzufügen, der..."
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Bitte im Format "Als... möchte ich... damit..."
      value: |
        **Als** [Rolle]
        **möchte ich** [Handlung]
        **damit** [Nutzen]
    validations:
      required: false

  - type: textarea
    id: criteria
    attributes:
      label: Akzeptanzkriterien
      description: Wann gilt das Feature als fertig?
      placeholder: "- [ ] Kriterium 1\n- [ ] Kriterium 2"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Design & Kontext
      description: Füge hier Links zu Mockups, Screenshots oder technische Hinweise ein.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      options:
        - Niedrig
        - Mittel
        - Hoch
    validations:
      required: true